<?php
return array(
    'books/edit/([0-9]+)' => 'books/edit/$1',
    'books/add' => 'books/add',
    'books/process' => 'books/process',
    'books/finished' => 'books/finished',
    'books/([0-9]+)' => 'books/view/$1',
    'books' => 'books/index',
    'games/edit' => 'games/edit',
    'games/add' => 'games/add',
    'games/process' => 'games/process',
    'games/finished' => 'games/finished',
    'games/([0-9]+)' => 'games/view/$1',
    'games' => 'games/index',
    'wants/edit' => 'wants/edit',
    'wants/add' => 'wants/add',
    'wants/process' => 'wants/process',
    'wants/finished' => 'wants/finished',
    'wants/([0-9]+)' => 'wants/view/$1',
    'wants' => 'wants/index',
    'deals/edit' => 'deals/edit',
    'deals/add' => 'deals/add',
    'deals/process' => 'deals/process',
    'deals/finished' => 'deals/finished',
    'deals/([0-9]+)' => 'deals/view/$1',
    'deals' => 'deals/index',
    'adminmvc' => 'site/index',
);